# Generated by Django 4.1.3 on 2023-03-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
