# Generated by Django 4.1.3 on 2023-03-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_delete_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('weight', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('userid', models.CharField(default='Saurav', max_length=200)),
                ('risk_score', models.IntegerField()),
                ('spam', models.IntegerField()),
                ('subject', models.CharField(max_length=10000)),
                ('body', models.CharField(max_length=10000)),
                ('sms', models.CharField(max_length=10000)),
            ],
            options={
                'unique_together': {('userid', 'contact')},
            },
        ),
    ]
