# Generated by Django 4.1.3 on 2023-03-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='sms',
            field=models.CharField(default=None, max_length=10000),
        ),
    ]
